org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:/Program Files/Java/jdk-17

RELEASE_STORE_PASSWORD=b8s7Ss6akK13g
RELEASE_KEY_PASSWORD=b8s7Ss6akK13g
RELEASE_KEY_ALIAS=booksea
RELEASE_STORE_FILE=C:\\Users\\Leonarda\\Keys\\booksea-upload.jks